packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - better-sqlite3
  - electron
  - es5-ext
  - esbuild
  - msgpackr-extract
  - sharp
  - sqlite3
  - uglifyjs-webpack-plugin
  - unrs-resolver
